/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCanvasParticleComponent {
    }
    interface MyCardskillComponent {
    }
    interface MyHomepage {
    }
    interface MyProjectsComponent {
    }
}
declare global {
    interface HTMLMyCanvasParticleComponentElement extends Components.MyCanvasParticleComponent, HTMLStencilElement {
    }
    var HTMLMyCanvasParticleComponentElement: {
        prototype: HTMLMyCanvasParticleComponentElement;
        new (): HTMLMyCanvasParticleComponentElement;
    };
    interface HTMLMyCardskillComponentElement extends Components.MyCardskillComponent, HTMLStencilElement {
    }
    var HTMLMyCardskillComponentElement: {
        prototype: HTMLMyCardskillComponentElement;
        new (): HTMLMyCardskillComponentElement;
    };
    interface HTMLMyHomepageElement extends Components.MyHomepage, HTMLStencilElement {
    }
    var HTMLMyHomepageElement: {
        prototype: HTMLMyHomepageElement;
        new (): HTMLMyHomepageElement;
    };
    interface HTMLMyProjectsComponentElement extends Components.MyProjectsComponent, HTMLStencilElement {
    }
    var HTMLMyProjectsComponentElement: {
        prototype: HTMLMyProjectsComponentElement;
        new (): HTMLMyProjectsComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-canvas-particle-component": HTMLMyCanvasParticleComponentElement;
        "my-cardskill-component": HTMLMyCardskillComponentElement;
        "my-homepage": HTMLMyHomepageElement;
        "my-projects-component": HTMLMyProjectsComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyCanvasParticleComponent {
    }
    interface MyCardskillComponent {
    }
    interface MyHomepage {
    }
    interface MyProjectsComponent {
    }
    interface IntrinsicElements {
        "my-canvas-particle-component": MyCanvasParticleComponent;
        "my-cardskill-component": MyCardskillComponent;
        "my-homepage": MyHomepage;
        "my-projects-component": MyProjectsComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-canvas-particle-component": LocalJSX.MyCanvasParticleComponent & JSXBase.HTMLAttributes<HTMLMyCanvasParticleComponentElement>;
            "my-cardskill-component": LocalJSX.MyCardskillComponent & JSXBase.HTMLAttributes<HTMLMyCardskillComponentElement>;
            "my-homepage": LocalJSX.MyHomepage & JSXBase.HTMLAttributes<HTMLMyHomepageElement>;
            "my-projects-component": LocalJSX.MyProjectsComponent & JSXBase.HTMLAttributes<HTMLMyProjectsComponentElement>;
        }
    }
}
